### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED issue

### ISSUE THREAD

**Issue by bhuone-garbu** [ryanmurakami/trash-panda-buffet#9]
I don't think this is an issue with code or serverless, but seems to be with dependencies with latest nodejs.

Running on node v14.5.0, I get:

```
ERROR in ./src/client/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /trash-panda-buffet/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:498:9)
    at resolveExports (internal/modules/cjs/loader.js:514:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:642:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1017:27)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
```

at the very end of the deploy script. The cloud formation and stacks seems to deploy properly but because of this, the API Gateway are completely broken

This similar to issues reported here.
https://github.com/babel/babel/issues/11216
https://github.com/nodejs/node/issues/32107

I tried bumping the version of babel dependencies which "seems to fix the issue" but there were still some others errors on my end which could be me fiddling around too much, so I can't guarantee that it has indeed fixed all dependency problem. I have yet to try and ascertain if the issue is only for nodejs > 12.

**Comment by javixeneize** [comment]
Same happens to me with node 12.18.

**Comment by tms2018** [comment]
The same happened for me with node 14.2.  I updated the @babel dependencies to the following and it fixed it. 

    "@babel/core": "^7.12.3",
    "@babel/plugin-proposal-class-properties": "^7.12.1",
    "@babel/preset-env": "^7.12.1",
    "@babel/preset-react": "^7.12.1",
